type: "vit_small_patch16_224"
url: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/vit_small_p16_224-15ec54c9.pth"
num_classes: 1000
input_size: [3, 224, 224]
pool_size: null
crop_pct: 0.9
interpolation: "bicubic"
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
first_conv: "patch_embed.proj"
classifier: "head"