ann_type: "single-label-class"
ann_name: "subject"
annf_train: "${oc.env:TSH}/splits/subject/train.csv"
annf_val: "${oc.env:TSH}/splits/subject/val.csv"
annf_test: "${oc.env:TSH}/splits/subject/test.csv"
attributes: "subject"
num_classes: 18
encoding_file: "${oc.env:TSH}/splits/subject/tsh_subject_label2id.yaml"