defaults:
  - dataset: hmdb51
  - model: videomae-base
  - training: default
  - evaluation: default
  - hardware: default
  - _self_

wandb:
  project: "VideoMAE Fourier Pretrain"

do_train: True
do_test: True

use_fourier: True

training:
  resume_from_checkpoint: null
  batch_size: 12

hardware:
  num_data_workers: 64

# model:  # Used for manually loading a testing checkpoint
#   name_or_path: "outputs/2024-11-21/14-33-41/MCG-NJU/videomae-small-finetuned-kinetics-finetuned-NTU-RGB+D60/checkpoint-156"

hydra:
  job: 
    chdir:  True
